using CountryCityProvinceDataLayer;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSprocGenerator.Data.SingleTable.Dto
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using CommonLibrary;
    
    
    [CommonLibrary.CustomAttributes.TableNameAttribute("City")]
    [DataContract]
    public class City
    {
        
        private string _name;
        
        private System.Nullable<int> _stateProvinceID;
        
        private System.Nullable<System.DateTime> _createdDate;
        
        private System.Guid _createdBy;
        
        private System.Nullable<System.DateTime> _updatedDate;
        
        private System.Guid _updatedBy;
        
        private string _cityCode;
        
        private System.Nullable<int> _countryID;    
       
       
        
        private int _cityID;
        
        private Dictionary<string, bool> _isModifiedDictionary = new Dictionary<string, bool>();
        
        public City()
        {
            this.InitializeIsModifiedDictionary();
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("Name")]
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
                this.SetIsModified("Name");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("StateProvinceID")]
        public virtual System.Nullable<int> StateProvinceID
        {
            get
            {
                return this._stateProvinceID;
            }
            set
            {
                this._stateProvinceID = value;
                this.SetIsModified("StateProvinceID");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("CreatedDate")]
        public virtual System.Nullable<System.DateTime> CreatedDate
        {
            get
            {
                return this._createdDate;
            }
            set
            {
                this._createdDate = value;
                this.SetIsModified("CreatedDate");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("CreatedBy")]
        public virtual System.Guid CreatedBy
        {
            get
            {
                return this._createdBy;
            }
            set
            {
                this._createdBy = value;
                this.SetIsModified("CreatedBy");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("UpdatedDate")]
        public virtual System.Nullable<System.DateTime> UpdatedDate
        {
            get
            {
                return this._updatedDate;
            }
            set
            {
                this._updatedDate = value;
                this.SetIsModified("UpdatedDate");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("UpdatedBy")]
        public virtual System.Guid UpdatedBy
        {
            get
            {
                return this._updatedBy;
            }
            set
            {
                this._updatedBy = value;
                this.SetIsModified("UpdatedBy");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("CityCode")]
        public virtual string CityCode
        {
            get
            {
                return this._cityCode;
            }
            set
            {
                this._cityCode = value;
                this.SetIsModified("CityCode");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("CountryID")]
        public virtual System.Nullable<int> CountryID
        {
            get
            {
                return this._countryID;
            }
            set
            {
                this._countryID = value;
                this.SetIsModified("CountryID");
            }
        }
        
       
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("CityID")]
        [CommonLibrary.CustomAttributes.PrimaryKey()]
        public virtual int CityID
        {
            get
            {
                return this._cityID;
            }
            set
            {
                this._cityID = value;
                this.SetIsModified("CityID");
            }
        }
        
        public virtual Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this._isModifiedDictionary;
            }
            set
            {
                this._isModifiedDictionary = value;
            }
        }
        
        private void InitializeIsModifiedDictionary()
        {
            this.IsModifiedDictionary.Add("Name", false);
            this.IsModifiedDictionary.Add("StateProvinceID", false);
            this.IsModifiedDictionary.Add("CreatedDate", false);
            this.IsModifiedDictionary.Add("CreatedBy", false);
            this.IsModifiedDictionary.Add("UpdatedDate", false);
            this.IsModifiedDictionary.Add("UpdatedBy", false);
            this.IsModifiedDictionary.Add("CityCode", false);
            this.IsModifiedDictionary.Add("CountryID", false);
            this.IsModifiedDictionary.Add("AlternateName", false);
            this.IsModifiedDictionary.Add("locationid", false);
            this.IsModifiedDictionary.Add("CityID", false);
        }
        
        private void SetIsModified(string columnName)
        {
            if ((this.IsModifiedDictionary.ContainsKey(columnName) == true))
            {
                IsModifiedDictionary[columnName] = true;
            }
        }
    }
}
