//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSprocGenerator.Data.SingleTable.Dto
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using CommonLibrary;
    
    
    [CommonLibrary.CustomAttributes.TableNameAttribute("Blog")]
    public class Blog
    {
        
        private System.Guid _profileIDOwner;
        
        private string _blogName;
        
        private string _blogDescription;
        
        private bool _deleted;
        
        private System.DateTime _insertedDateTime;
        
        private System.DateTime _modifiedDateTime;
        
        private System.Guid _blogID;
        
        private Dictionary<string, bool> _isModifiedDictionary = new Dictionary<string, bool>();
        
        public Blog()
        {
            this.InitializeIsModifiedDictionary();
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ProfileIDOwner")]
        public virtual System.Guid ProfileIDOwner
        {
            get
            {
                return this._profileIDOwner;
            }
            set
            {
                this._profileIDOwner = value;
                this.SetIsModified("ProfileIDOwner");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("BlogName")]
        public virtual string BlogName
        {
            get
            {
                return this._blogName;
            }
            set
            {
                this._blogName = value;
                this.SetIsModified("BlogName");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("BlogDescription")]
        public virtual string BlogDescription
        {
            get
            {
                return this._blogDescription;
            }
            set
            {
                this._blogDescription = value;
                this.SetIsModified("BlogDescription");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("Deleted")]
        public virtual bool Deleted
        {
            get
            {
                return this._deleted;
            }
            set
            {
                this._deleted = value;
                this.SetIsModified("Deleted");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("InsertedDateTime")]
        public virtual System.DateTime InsertedDateTime
        {
            get
            {
                return this._insertedDateTime;
            }
            set
            {
                this._insertedDateTime = value;
                this.SetIsModified("InsertedDateTime");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ModifiedDateTime")]
        public virtual System.DateTime ModifiedDateTime
        {
            get
            {
                return this._modifiedDateTime;
            }
            set
            {
                this._modifiedDateTime = value;
                this.SetIsModified("ModifiedDateTime");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("BlogID")]
        [CommonLibrary.CustomAttributes.PrimaryKey()]
        public virtual System.Guid BlogID
        {
            get
            {
                return this._blogID;
            }
            set
            {
                this._blogID = value;
                this.SetIsModified("BlogID");
            }
        }
        
        public virtual Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this._isModifiedDictionary;
            }
            set
            {
                this._isModifiedDictionary = value;
            }
        }
        
        private void InitializeIsModifiedDictionary()
        {
            this.IsModifiedDictionary.Add("ProfileIDOwner", false);
            this.IsModifiedDictionary.Add("BlogName", false);
            this.IsModifiedDictionary.Add("BlogDescription", false);
            this.IsModifiedDictionary.Add("Deleted", false);
            this.IsModifiedDictionary.Add("InsertedDateTime", false);
            this.IsModifiedDictionary.Add("ModifiedDateTime", false);
            this.IsModifiedDictionary.Add("BlogID", false);
        }
        
        private void SetIsModified(string columnName)
        {
            if ((this.IsModifiedDictionary.ContainsKey(columnName) == true))
            {
                IsModifiedDictionary[columnName] = true;
            }
        }
    }
}
