//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSprocGenerator.Data.SingleTable.Dto
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using CommonLibrary;
    
    
    [CommonLibrary.CustomAttributes.TableNameAttribute("Categories")]
    public class Categories
    {
        
        private string _categoryName;
        
        private string _description;
        
        private System.Drawing.Image _picture;
        
        private int _categoryID;
        
        private Dictionary<string, bool> _isModifiedDictionary = new Dictionary<string, bool>();
        
        public Categories()
        {
            this.InitializeIsModifiedDictionary();
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("CategoryName")]
        public virtual string CategoryName
        {
            get
            {
                return this._categoryName;
            }
            set
            {
                this._categoryName = value;
                this.SetIsModified("CategoryName");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("Description")]
        public virtual string Description
        {
            get
            {
                return this._description;
            }
            set
            {
                this._description = value;
                this.SetIsModified("Description");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("Picture")]
        public virtual System.Drawing.Image Picture
        {
            get
            {
                return this._picture;
            }
            set
            {
                this._picture = value;
                this.SetIsModified("Picture");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("CategoryID")]
        [CommonLibrary.CustomAttributes.PrimaryKey()]
        public virtual int CategoryID
        {
            get
            {
                return this._categoryID;
            }
            set
            {
                this._categoryID = value;
                this.SetIsModified("CategoryID");
            }
        }
        
        public virtual Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this._isModifiedDictionary;
            }
            set
            {
                this._isModifiedDictionary = value;
            }
        }
        
        private void InitializeIsModifiedDictionary()
        {
            this.IsModifiedDictionary.Add("CategoryName", false);
            this.IsModifiedDictionary.Add("Description", false);
            this.IsModifiedDictionary.Add("Picture", false);
            this.IsModifiedDictionary.Add("CategoryID", false);
        }
        
        private void SetIsModified(string columnName)
        {
            if ((this.IsModifiedDictionary.ContainsKey(columnName) == true))
            {
                IsModifiedDictionary[columnName] = true;
            }
        }
    }
}
