//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSprocGenerator.Data.SingleTable.Dto
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using CommonLibrary;
    
    
    [CommonLibrary.CustomAttributes.TableNameAttribute("CountryName")]
    public class CountryName
    {
        
        private short _countryID;
        
        private string _name;
        
        private int _countryNameID;
        
        private Dictionary<string, bool> _isModifiedDictionary = new Dictionary<string, bool>();
        
        public CountryName()
        {
            this.InitializeIsModifiedDictionary();
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("CountryID")]
        public virtual short CountryID
        {
            get
            {
                return this._countryID;
            }
            set
            {
                this._countryID = value;
                this.SetIsModified("CountryID");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("Name")]
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
                this.SetIsModified("Name");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("CountryNameID")]
        [CommonLibrary.CustomAttributes.PrimaryKey()]
        public virtual int CountryNameID
        {
            get
            {
                return this._countryNameID;
            }
            set
            {
                this._countryNameID = value;
                this.SetIsModified("CountryNameID");
            }
        }
        
        public virtual Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this._isModifiedDictionary;
            }
            set
            {
                this._isModifiedDictionary = value;
            }
        }
        
        private void InitializeIsModifiedDictionary()
        {
            this.IsModifiedDictionary.Add("CountryID", false);
            this.IsModifiedDictionary.Add("Name", false);
            this.IsModifiedDictionary.Add("CountryNameID", false);
        }
        
        private void SetIsModified(string columnName)
        {
            if ((this.IsModifiedDictionary.ContainsKey(columnName) == true))
            {
                IsModifiedDictionary[columnName] = true;
            }
        }
    }
}
