//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSprocGenerator.Data.SingleTable.Dto
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using CommonLibrary;
    
    
    [CommonLibrary.CustomAttributes.TableNameAttribute("Employees")]
    public class Employees
    {
        
        private string _lastName;
        
        private string _firstName;
        
        private string _title;
        
        private string _titleOfCourtesy;
        
        private System.Nullable<System.DateTime> _birthDate;
        
        private System.Nullable<System.DateTime> _hireDate;
        
        private string _address;
        
        private string _city;
        
        private string _region;
        
        private string _postalCode;
        
        private string _country;
        
        private string _homePhone;
        
        private string _extension;
        
        private System.Drawing.Image _photo;
        
        private string _notes;
        
        private System.Nullable<int> _reportsTo;
        
        private string _photoPath;
        
        private int _employeeID;
        
        private Dictionary<string, bool> _isModifiedDictionary = new Dictionary<string, bool>();
        
        public Employees()
        {
            this.InitializeIsModifiedDictionary();
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("LastName")]
        public virtual string LastName
        {
            get
            {
                return this._lastName;
            }
            set
            {
                this._lastName = value;
                this.SetIsModified("LastName");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("FirstName")]
        public virtual string FirstName
        {
            get
            {
                return this._firstName;
            }
            set
            {
                this._firstName = value;
                this.SetIsModified("FirstName");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("Title")]
        public virtual string Title
        {
            get
            {
                return this._title;
            }
            set
            {
                this._title = value;
                this.SetIsModified("Title");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("TitleOfCourtesy")]
        public virtual string TitleOfCourtesy
        {
            get
            {
                return this._titleOfCourtesy;
            }
            set
            {
                this._titleOfCourtesy = value;
                this.SetIsModified("TitleOfCourtesy");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("BirthDate")]
        public virtual System.Nullable<System.DateTime> BirthDate
        {
            get
            {
                return this._birthDate;
            }
            set
            {
                this._birthDate = value;
                this.SetIsModified("BirthDate");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("HireDate")]
        public virtual System.Nullable<System.DateTime> HireDate
        {
            get
            {
                return this._hireDate;
            }
            set
            {
                this._hireDate = value;
                this.SetIsModified("HireDate");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("Address")]
        public virtual string Address
        {
            get
            {
                return this._address;
            }
            set
            {
                this._address = value;
                this.SetIsModified("Address");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("City")]
        public virtual string City
        {
            get
            {
                return this._city;
            }
            set
            {
                this._city = value;
                this.SetIsModified("City");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("Region")]
        public virtual string Region
        {
            get
            {
                return this._region;
            }
            set
            {
                this._region = value;
                this.SetIsModified("Region");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("PostalCode")]
        public virtual string PostalCode
        {
            get
            {
                return this._postalCode;
            }
            set
            {
                this._postalCode = value;
                this.SetIsModified("PostalCode");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("Country")]
        public virtual string Country
        {
            get
            {
                return this._country;
            }
            set
            {
                this._country = value;
                this.SetIsModified("Country");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("HomePhone")]
        public virtual string HomePhone
        {
            get
            {
                return this._homePhone;
            }
            set
            {
                this._homePhone = value;
                this.SetIsModified("HomePhone");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("Extension")]
        public virtual string Extension
        {
            get
            {
                return this._extension;
            }
            set
            {
                this._extension = value;
                this.SetIsModified("Extension");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("Photo")]
        public virtual System.Drawing.Image Photo
        {
            get
            {
                return this._photo;
            }
            set
            {
                this._photo = value;
                this.SetIsModified("Photo");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("Notes")]
        public virtual string Notes
        {
            get
            {
                return this._notes;
            }
            set
            {
                this._notes = value;
                this.SetIsModified("Notes");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ReportsTo")]
        public virtual System.Nullable<int> ReportsTo
        {
            get
            {
                return this._reportsTo;
            }
            set
            {
                this._reportsTo = value;
                this.SetIsModified("ReportsTo");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("PhotoPath")]
        public virtual string PhotoPath
        {
            get
            {
                return this._photoPath;
            }
            set
            {
                this._photoPath = value;
                this.SetIsModified("PhotoPath");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("EmployeeID")]
        [CommonLibrary.CustomAttributes.PrimaryKey()]
        public virtual int EmployeeID
        {
            get
            {
                return this._employeeID;
            }
            set
            {
                this._employeeID = value;
                this.SetIsModified("EmployeeID");
            }
        }
        
        public virtual Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this._isModifiedDictionary;
            }
            set
            {
                this._isModifiedDictionary = value;
            }
        }
        
        private void InitializeIsModifiedDictionary()
        {
            this.IsModifiedDictionary.Add("LastName", false);
            this.IsModifiedDictionary.Add("FirstName", false);
            this.IsModifiedDictionary.Add("Title", false);
            this.IsModifiedDictionary.Add("TitleOfCourtesy", false);
            this.IsModifiedDictionary.Add("BirthDate", false);
            this.IsModifiedDictionary.Add("HireDate", false);
            this.IsModifiedDictionary.Add("Address", false);
            this.IsModifiedDictionary.Add("City", false);
            this.IsModifiedDictionary.Add("Region", false);
            this.IsModifiedDictionary.Add("PostalCode", false);
            this.IsModifiedDictionary.Add("Country", false);
            this.IsModifiedDictionary.Add("HomePhone", false);
            this.IsModifiedDictionary.Add("Extension", false);
            this.IsModifiedDictionary.Add("Photo", false);
            this.IsModifiedDictionary.Add("Notes", false);
            this.IsModifiedDictionary.Add("ReportsTo", false);
            this.IsModifiedDictionary.Add("PhotoPath", false);
            this.IsModifiedDictionary.Add("EmployeeID", false);
        }
        
        private void SetIsModified(string columnName)
        {
            if ((this.IsModifiedDictionary.ContainsKey(columnName) == true))
            {
                IsModifiedDictionary[columnName] = true;
            }
        }
    }
}
