//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSprocGenerator.Data.SingleTable.Dto
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using CommonLibrary;
    
    
    [CommonLibrary.CustomAttributes.TableNameAttribute("Orders")]
    public class Orders
    {
        
        private string _customerID;
        
        private System.Nullable<int> _employeeID;
        
        private System.Nullable<System.DateTime> _orderDate;
        
        private System.Nullable<System.DateTime> _requiredDate;
        
        private System.Nullable<System.DateTime> _shippedDate;
        
        private System.Nullable<int> _shipVia;
        
        private System.Nullable<decimal> _freight;
        
        private string _shipName;
        
        private string _shipAddress;
        
        private string _shipCity;
        
        private string _shipRegion;
        
        private string _shipPostalCode;
        
        private string _shipCountry;
        
        private int _orderID;
        
        private Dictionary<string, bool> _isModifiedDictionary = new Dictionary<string, bool>();
        
        public Orders()
        {
            this.InitializeIsModifiedDictionary();
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("CustomerID")]
        public virtual string CustomerID
        {
            get
            {
                return this._customerID;
            }
            set
            {
                this._customerID = value;
                this.SetIsModified("CustomerID");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("EmployeeID")]
        public virtual System.Nullable<int> EmployeeID
        {
            get
            {
                return this._employeeID;
            }
            set
            {
                this._employeeID = value;
                this.SetIsModified("EmployeeID");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("OrderDate")]
        public virtual System.Nullable<System.DateTime> OrderDate
        {
            get
            {
                return this._orderDate;
            }
            set
            {
                this._orderDate = value;
                this.SetIsModified("OrderDate");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("RequiredDate")]
        public virtual System.Nullable<System.DateTime> RequiredDate
        {
            get
            {
                return this._requiredDate;
            }
            set
            {
                this._requiredDate = value;
                this.SetIsModified("RequiredDate");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ShippedDate")]
        public virtual System.Nullable<System.DateTime> ShippedDate
        {
            get
            {
                return this._shippedDate;
            }
            set
            {
                this._shippedDate = value;
                this.SetIsModified("ShippedDate");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ShipVia")]
        public virtual System.Nullable<int> ShipVia
        {
            get
            {
                return this._shipVia;
            }
            set
            {
                this._shipVia = value;
                this.SetIsModified("ShipVia");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("Freight")]
        public virtual System.Nullable<decimal> Freight
        {
            get
            {
                return this._freight;
            }
            set
            {
                this._freight = value;
                this.SetIsModified("Freight");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ShipName")]
        public virtual string ShipName
        {
            get
            {
                return this._shipName;
            }
            set
            {
                this._shipName = value;
                this.SetIsModified("ShipName");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ShipAddress")]
        public virtual string ShipAddress
        {
            get
            {
                return this._shipAddress;
            }
            set
            {
                this._shipAddress = value;
                this.SetIsModified("ShipAddress");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ShipCity")]
        public virtual string ShipCity
        {
            get
            {
                return this._shipCity;
            }
            set
            {
                this._shipCity = value;
                this.SetIsModified("ShipCity");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ShipRegion")]
        public virtual string ShipRegion
        {
            get
            {
                return this._shipRegion;
            }
            set
            {
                this._shipRegion = value;
                this.SetIsModified("ShipRegion");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ShipPostalCode")]
        public virtual string ShipPostalCode
        {
            get
            {
                return this._shipPostalCode;
            }
            set
            {
                this._shipPostalCode = value;
                this.SetIsModified("ShipPostalCode");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ShipCountry")]
        public virtual string ShipCountry
        {
            get
            {
                return this._shipCountry;
            }
            set
            {
                this._shipCountry = value;
                this.SetIsModified("ShipCountry");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("OrderID")]
        [CommonLibrary.CustomAttributes.PrimaryKey()]
        public virtual int OrderID
        {
            get
            {
                return this._orderID;
            }
            set
            {
                this._orderID = value;
                this.SetIsModified("OrderID");
            }
        }
        
        public virtual Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this._isModifiedDictionary;
            }
            set
            {
                this._isModifiedDictionary = value;
            }
        }
        
        private void InitializeIsModifiedDictionary()
        {
            this.IsModifiedDictionary.Add("CustomerID", false);
            this.IsModifiedDictionary.Add("EmployeeID", false);
            this.IsModifiedDictionary.Add("OrderDate", false);
            this.IsModifiedDictionary.Add("RequiredDate", false);
            this.IsModifiedDictionary.Add("ShippedDate", false);
            this.IsModifiedDictionary.Add("ShipVia", false);
            this.IsModifiedDictionary.Add("Freight", false);
            this.IsModifiedDictionary.Add("ShipName", false);
            this.IsModifiedDictionary.Add("ShipAddress", false);
            this.IsModifiedDictionary.Add("ShipCity", false);
            this.IsModifiedDictionary.Add("ShipRegion", false);
            this.IsModifiedDictionary.Add("ShipPostalCode", false);
            this.IsModifiedDictionary.Add("ShipCountry", false);
            this.IsModifiedDictionary.Add("OrderID", false);
        }
        
        private void SetIsModified(string columnName)
        {
            if ((this.IsModifiedDictionary.ContainsKey(columnName) == true))
            {
                IsModifiedDictionary[columnName] = true;
            }
        }
    }
}
