//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSprocGenerator.Data.SingleTable.Dto
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using CommonLibrary;
    
    
    [CommonLibrary.CustomAttributes.TableNameAttribute("Parent_Child")]
    public class Parent_Child
    {
        
        private System.Guid _parent_ChildID;
        
        private System.Guid _parent_ProfileID;
        
        private System.Guid _child_ProfileID;
        
        private Dictionary<string, bool> _isModifiedDictionary = new Dictionary<string, bool>();
        
        public Parent_Child()
        {
            this.InitializeIsModifiedDictionary();
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("Parent_ChildID")]
        public virtual System.Guid Parent_ChildID
        {
            get
            {
                return this._parent_ChildID;
            }
            set
            {
                this._parent_ChildID = value;
                this.SetIsModified("Parent_ChildID");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("Parent_ProfileID")]
        [CommonLibrary.CustomAttributes.PrimaryKey()]
        public virtual System.Guid Parent_ProfileID
        {
            get
            {
                return this._parent_ProfileID;
            }
            set
            {
                this._parent_ProfileID = value;
                this.SetIsModified("Parent_ProfileID");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("Child_ProfileID")]
        [CommonLibrary.CustomAttributes.PrimaryKey()]
        public virtual System.Guid Child_ProfileID
        {
            get
            {
                return this._child_ProfileID;
            }
            set
            {
                this._child_ProfileID = value;
                this.SetIsModified("Child_ProfileID");
            }
        }
        
        public virtual Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this._isModifiedDictionary;
            }
            set
            {
                this._isModifiedDictionary = value;
            }
        }
        
        private void InitializeIsModifiedDictionary()
        {
            this.IsModifiedDictionary.Add("Parent_ChildID", false);
            this.IsModifiedDictionary.Add("Parent_ProfileID", false);
            this.IsModifiedDictionary.Add("Child_ProfileID", false);
        }
        
        private void SetIsModified(string columnName)
        {
            if ((this.IsModifiedDictionary.ContainsKey(columnName) == true))
            {
                IsModifiedDictionary[columnName] = true;
            }
        }
    }
}
