//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSprocGenerator.Data.SingleTable.Dto
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using CommonLibrary;
    
    
    [CommonLibrary.CustomAttributes.TableNameAttribute("Region")]
    public class Region
    {
        
        private string _regionDescription;
        
        private int _regionID;
        
        private Dictionary<string, bool> _isModifiedDictionary = new Dictionary<string, bool>();
        
        public Region()
        {
            this.InitializeIsModifiedDictionary();
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("RegionDescription")]
        public virtual string RegionDescription
        {
            get
            {
                return this._regionDescription;
            }
            set
            {
                this._regionDescription = value;
                this.SetIsModified("RegionDescription");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("RegionID")]
        [CommonLibrary.CustomAttributes.PrimaryKey()]
        public virtual int RegionID
        {
            get
            {
                return this._regionID;
            }
            set
            {
                this._regionID = value;
                this.SetIsModified("RegionID");
            }
        }
        
        public virtual Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this._isModifiedDictionary;
            }
            set
            {
                this._isModifiedDictionary = value;
            }
        }
        
        private void InitializeIsModifiedDictionary()
        {
            this.IsModifiedDictionary.Add("RegionDescription", false);
            this.IsModifiedDictionary.Add("RegionID", false);
        }
        
        private void SetIsModified(string columnName)
        {
            if ((this.IsModifiedDictionary.ContainsKey(columnName) == true))
            {
                IsModifiedDictionary[columnName] = true;
            }
        }
    }
}
