//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSprocGenerator.Data.SingleTable.Dto
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using CommonLibrary;
    
    
    [CommonLibrary.CustomAttributes.TableNameAttribute("Shippers")]
    public class Shippers
    {
        
        private string _companyName;
        
        private string _phone;
        
        private int _shipperID;
        
        private Dictionary<string, bool> _isModifiedDictionary = new Dictionary<string, bool>();
        
        public Shippers()
        {
            this.InitializeIsModifiedDictionary();
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("CompanyName")]
        public virtual string CompanyName
        {
            get
            {
                return this._companyName;
            }
            set
            {
                this._companyName = value;
                this.SetIsModified("CompanyName");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("Phone")]
        public virtual string Phone
        {
            get
            {
                return this._phone;
            }
            set
            {
                this._phone = value;
                this.SetIsModified("Phone");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ShipperID")]
        [CommonLibrary.CustomAttributes.PrimaryKey()]
        public virtual int ShipperID
        {
            get
            {
                return this._shipperID;
            }
            set
            {
                this._shipperID = value;
                this.SetIsModified("ShipperID");
            }
        }
        
        public virtual Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this._isModifiedDictionary;
            }
            set
            {
                this._isModifiedDictionary = value;
            }
        }
        
        private void InitializeIsModifiedDictionary()
        {
            this.IsModifiedDictionary.Add("CompanyName", false);
            this.IsModifiedDictionary.Add("Phone", false);
            this.IsModifiedDictionary.Add("ShipperID", false);
        }
        
        private void SetIsModified(string columnName)
        {
            if ((this.IsModifiedDictionary.ContainsKey(columnName) == true))
            {
                IsModifiedDictionary[columnName] = true;
            }
        }
    }
}
