//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSprocGenerator.Data.SingleTable.Dto
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using CommonLibrary;
    
    
    [CommonLibrary.CustomAttributes.TableNameAttribute("Territories")]
    public class Territories
    {
        
        private string _territoryDescription;
        
        private int _regionID;
        
        private string _territoryID;
        
        private Dictionary<string, bool> _isModifiedDictionary = new Dictionary<string, bool>();
        
        public Territories()
        {
            this.InitializeIsModifiedDictionary();
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("TerritoryDescription")]
        public virtual string TerritoryDescription
        {
            get
            {
                return this._territoryDescription;
            }
            set
            {
                this._territoryDescription = value;
                this.SetIsModified("TerritoryDescription");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("RegionID")]
        public virtual int RegionID
        {
            get
            {
                return this._regionID;
            }
            set
            {
                this._regionID = value;
                this.SetIsModified("RegionID");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("TerritoryID")]
        [CommonLibrary.CustomAttributes.PrimaryKey()]
        public virtual string TerritoryID
        {
            get
            {
                return this._territoryID;
            }
            set
            {
                this._territoryID = value;
                this.SetIsModified("TerritoryID");
            }
        }
        
        public virtual Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this._isModifiedDictionary;
            }
            set
            {
                this._isModifiedDictionary = value;
            }
        }
        
        private void InitializeIsModifiedDictionary()
        {
            this.IsModifiedDictionary.Add("TerritoryDescription", false);
            this.IsModifiedDictionary.Add("RegionID", false);
            this.IsModifiedDictionary.Add("TerritoryID", false);
        }
        
        private void SetIsModified(string columnName)
        {
            if ((this.IsModifiedDictionary.ContainsKey(columnName) == true))
            {
                IsModifiedDictionary[columnName] = true;
            }
        }
    }
}
