//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSprocGenerator.Data.SingleTable.Dto
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using CommonLibrary;
    
    
    [CommonLibrary.CustomAttributes.TableNameAttribute("WebsiteLinkAccessRequest")]
    public class WebsiteLinkAccessRequest
    {
        
        private System.Guid _websiteLinkAccessRequestID;
        
        private System.Guid _websiteLinkID;
        
        private bool _approved;
        
        private bool _deleted;
        
        private System.DateTime _insertedDateTime;
        
        private System.DateTime _modifiedDateTime;
        
        private System.Guid _profileIDChild;
        
        private System.Guid _profileIDParent;
        
        private System.Guid _profileIDOtherProfileID;
        
        private Dictionary<string, bool> _isModifiedDictionary = new Dictionary<string, bool>();
        
        public WebsiteLinkAccessRequest()
        {
            this.InitializeIsModifiedDictionary();
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("WebsiteLinkAccessRequestID")]
        public virtual System.Guid WebsiteLinkAccessRequestID
        {
            get
            {
                return this._websiteLinkAccessRequestID;
            }
            set
            {
                this._websiteLinkAccessRequestID = value;
                this.SetIsModified("WebsiteLinkAccessRequestID");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("WebsiteLinkID")]
        public virtual System.Guid WebsiteLinkID
        {
            get
            {
                return this._websiteLinkID;
            }
            set
            {
                this._websiteLinkID = value;
                this.SetIsModified("WebsiteLinkID");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("Approved")]
        public virtual bool Approved
        {
            get
            {
                return this._approved;
            }
            set
            {
                this._approved = value;
                this.SetIsModified("Approved");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("Deleted")]
        public virtual bool Deleted
        {
            get
            {
                return this._deleted;
            }
            set
            {
                this._deleted = value;
                this.SetIsModified("Deleted");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("InsertedDateTime")]
        public virtual System.DateTime InsertedDateTime
        {
            get
            {
                return this._insertedDateTime;
            }
            set
            {
                this._insertedDateTime = value;
                this.SetIsModified("InsertedDateTime");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ModifiedDateTime")]
        public virtual System.DateTime ModifiedDateTime
        {
            get
            {
                return this._modifiedDateTime;
            }
            set
            {
                this._modifiedDateTime = value;
                this.SetIsModified("ModifiedDateTime");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ProfileIDChild")]
        [CommonLibrary.CustomAttributes.PrimaryKey()]
        public virtual System.Guid ProfileIDChild
        {
            get
            {
                return this._profileIDChild;
            }
            set
            {
                this._profileIDChild = value;
                this.SetIsModified("ProfileIDChild");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ProfileIDParent")]
        [CommonLibrary.CustomAttributes.PrimaryKey()]
        public virtual System.Guid ProfileIDParent
        {
            get
            {
                return this._profileIDParent;
            }
            set
            {
                this._profileIDParent = value;
                this.SetIsModified("ProfileIDParent");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ProfileIDOtherProfileID")]
        [CommonLibrary.CustomAttributes.PrimaryKey()]
        public virtual System.Guid ProfileIDOtherProfileID
        {
            get
            {
                return this._profileIDOtherProfileID;
            }
            set
            {
                this._profileIDOtherProfileID = value;
                this.SetIsModified("ProfileIDOtherProfileID");
            }
        }
        
        public virtual Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this._isModifiedDictionary;
            }
            set
            {
                this._isModifiedDictionary = value;
            }
        }
        
        private void InitializeIsModifiedDictionary()
        {
            this.IsModifiedDictionary.Add("WebsiteLinkAccessRequestID", false);
            this.IsModifiedDictionary.Add("WebsiteLinkID", false);
            this.IsModifiedDictionary.Add("Approved", false);
            this.IsModifiedDictionary.Add("Deleted", false);
            this.IsModifiedDictionary.Add("InsertedDateTime", false);
            this.IsModifiedDictionary.Add("ModifiedDateTime", false);
            this.IsModifiedDictionary.Add("ProfileIDChild", false);
            this.IsModifiedDictionary.Add("ProfileIDParent", false);
            this.IsModifiedDictionary.Add("ProfileIDOtherProfileID", false);
        }
        
        private void SetIsModified(string columnName)
        {
            if ((this.IsModifiedDictionary.ContainsKey(columnName) == true))
            {
                IsModifiedDictionary[columnName] = true;
            }
        }
    }
}
