//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSprocGenerator.Data.SingleTable.Dto
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using CommonLibrary;
    
    
    [CommonLibrary.CustomAttributes.TableNameAttribute("LibraryAccessRequest")]
    public class LibraryAccessRequest
    {
        
        private System.Guid _libraryAccessRequestID;
        
        private bool _approved;
        
        private bool _deleted;
        
        private System.DateTime _insertedDateTime;
        
        private System.DateTime _modifiedDateTime;
        
        private System.Guid _profileIDChild;
        
        private System.Guid _profileIDParent;
        
        private System.Guid _profileIDOtherProfile;
        
        private System.Guid _libraryID;
        
        private Dictionary<string, bool> _isModifiedDictionary = new Dictionary<string, bool>();
        
        public LibraryAccessRequest()
        {
            this.InitializeIsModifiedDictionary();
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("LibraryAccessRequestID")]
        public virtual System.Guid LibraryAccessRequestID
        {
            get
            {
                return this._libraryAccessRequestID;
            }
            set
            {
                this._libraryAccessRequestID = value;
                this.SetIsModified("LibraryAccessRequestID");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("Approved")]
        public virtual bool Approved
        {
            get
            {
                return this._approved;
            }
            set
            {
                this._approved = value;
                this.SetIsModified("Approved");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("Deleted")]
        public virtual bool Deleted
        {
            get
            {
                return this._deleted;
            }
            set
            {
                this._deleted = value;
                this.SetIsModified("Deleted");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("InsertedDateTime")]
        public virtual System.DateTime InsertedDateTime
        {
            get
            {
                return this._insertedDateTime;
            }
            set
            {
                this._insertedDateTime = value;
                this.SetIsModified("InsertedDateTime");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ModifiedDateTime")]
        public virtual System.DateTime ModifiedDateTime
        {
            get
            {
                return this._modifiedDateTime;
            }
            set
            {
                this._modifiedDateTime = value;
                this.SetIsModified("ModifiedDateTime");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ProfileIDChild")]
        [CommonLibrary.CustomAttributes.PrimaryKey()]
        public virtual System.Guid ProfileIDChild
        {
            get
            {
                return this._profileIDChild;
            }
            set
            {
                this._profileIDChild = value;
                this.SetIsModified("ProfileIDChild");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ProfileIDParent")]
        [CommonLibrary.CustomAttributes.PrimaryKey()]
        public virtual System.Guid ProfileIDParent
        {
            get
            {
                return this._profileIDParent;
            }
            set
            {
                this._profileIDParent = value;
                this.SetIsModified("ProfileIDParent");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ProfileIDOtherProfile")]
        [CommonLibrary.CustomAttributes.PrimaryKey()]
        public virtual System.Guid ProfileIDOtherProfile
        {
            get
            {
                return this._profileIDOtherProfile;
            }
            set
            {
                this._profileIDOtherProfile = value;
                this.SetIsModified("ProfileIDOtherProfile");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("LibraryID")]
        [CommonLibrary.CustomAttributes.PrimaryKey()]
        public virtual System.Guid LibraryID
        {
            get
            {
                return this._libraryID;
            }
            set
            {
                this._libraryID = value;
                this.SetIsModified("LibraryID");
            }
        }
        
        public virtual Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this._isModifiedDictionary;
            }
            set
            {
                this._isModifiedDictionary = value;
            }
        }
        
        private void InitializeIsModifiedDictionary()
        {
            this.IsModifiedDictionary.Add("LibraryAccessRequestID", false);
            this.IsModifiedDictionary.Add("Approved", false);
            this.IsModifiedDictionary.Add("Deleted", false);
            this.IsModifiedDictionary.Add("InsertedDateTime", false);
            this.IsModifiedDictionary.Add("ModifiedDateTime", false);
            this.IsModifiedDictionary.Add("ProfileIDChild", false);
            this.IsModifiedDictionary.Add("ProfileIDParent", false);
            this.IsModifiedDictionary.Add("ProfileIDOtherProfile", false);
            this.IsModifiedDictionary.Add("LibraryID", false);
        }
        
        private void SetIsModified(string columnName)
        {
            if ((this.IsModifiedDictionary.ContainsKey(columnName) == true))
            {
                IsModifiedDictionary[columnName] = true;
            }
        }
    }
}
