//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSprocGenerator.Data.SingleTable.Dto
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using CommonLibrary;
    
    
    [CommonLibrary.CustomAttributes.TableNameAttribute("Account")]
    public class Account
    {
        
        private string _accountCode;
        
        private string _accountUsername;
        
        private string _accountPassword;
        
        private bool _deleted;
        
        private System.DateTime _insertedDateTime;
        
        private System.DateTime _modifiedDateTime;
        
        private System.Guid _accountID;
        
        private Dictionary<string, bool> _isModifiedDictionary = new Dictionary<string, bool>();
        
        public Account()
        {
            this.InitializeIsModifiedDictionary();
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("AccountCode")]
        public virtual string AccountCode
        {
            get
            {
                return this._accountCode;
            }
            set
            {
                this._accountCode = value;
                this.SetIsModified("AccountCode");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("AccountUsername")]
        public virtual string AccountUsername
        {
            get
            {
                return this._accountUsername;
            }
            set
            {
                this._accountUsername = value;
                this.SetIsModified("AccountUsername");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("AccountPassword")]
        public virtual string AccountPassword
        {
            get
            {
                return this._accountPassword;
            }
            set
            {
                this._accountPassword = value;
                this.SetIsModified("AccountPassword");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("Deleted")]
        public virtual bool Deleted
        {
            get
            {
                return this._deleted;
            }
            set
            {
                this._deleted = value;
                this.SetIsModified("Deleted");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("InsertedDateTime")]
        public virtual System.DateTime InsertedDateTime
        {
            get
            {
                return this._insertedDateTime;
            }
            set
            {
                this._insertedDateTime = value;
                this.SetIsModified("InsertedDateTime");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ModifiedDateTime")]
        public virtual System.DateTime ModifiedDateTime
        {
            get
            {
                return this._modifiedDateTime;
            }
            set
            {
                this._modifiedDateTime = value;
                this.SetIsModified("ModifiedDateTime");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("AccountID")]
        [CommonLibrary.CustomAttributes.PrimaryKey()]
        public virtual System.Guid AccountID
        {
            get
            {
                return this._accountID;
            }
            set
            {
                this._accountID = value;
                this.SetIsModified("AccountID");
            }
        }
        
        public virtual Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this._isModifiedDictionary;
            }
            set
            {
                this._isModifiedDictionary = value;
            }
        }
        
        private void InitializeIsModifiedDictionary()
        {
            this.IsModifiedDictionary.Add("AccountCode", false);
            this.IsModifiedDictionary.Add("AccountUsername", false);
            this.IsModifiedDictionary.Add("AccountPassword", false);
            this.IsModifiedDictionary.Add("Deleted", false);
            this.IsModifiedDictionary.Add("InsertedDateTime", false);
            this.IsModifiedDictionary.Add("ModifiedDateTime", false);
            this.IsModifiedDictionary.Add("AccountID", false);
        }
        
        private void SetIsModified(string columnName)
        {
            if ((this.IsModifiedDictionary.ContainsKey(columnName) == true))
            {
                IsModifiedDictionary[columnName] = true;
            }
        }
    }
}
