//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSprocGenerator.Data.SingleTable.Dto
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using CommonLibrary;
    using System.Runtime.Serialization;
    
    [DataContract]
    [CommonLibrary.CustomAttributes.TableNameAttribute("Address")]
    public class Address
    {
        
        private System.Guid _addressTypeID;
        
        private string _addressStreet;
        
        private string _addressCity;
        
        private string _addressZipCode;
        
        private string _addressCountry;
        
        private bool _deleted;
        
        private System.DateTime _insertedDateTime;
        
        private System.DateTime _modifiedDateTime;
        
        private System.Guid _addressID;
        
        private Dictionary<string, bool> _isModifiedDictionary = new Dictionary<string, bool>();
        
        public Address()
        {
            this.InitializeIsModifiedDictionary();
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("AddressTypeID")]
        public virtual System.Guid AddressTypeID
        {
            get
            {
                return this._addressTypeID;
            }
            set
            {
                this._addressTypeID = value;
                this.SetIsModified("AddressTypeID");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("AddressStreet")]
        public virtual string AddressStreet
        {
            get
            {
                return this._addressStreet;
            }
            set
            {
                this._addressStreet = value;
                this.SetIsModified("AddressStreet");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("AddressCity")]
        public virtual string AddressCity
        {
            get
            {
                return this._addressCity;
            }
            set
            {
                this._addressCity = value;
                this.SetIsModified("AddressCity");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("AddressZipCode")]
        public virtual string AddressZipCode
        {
            get
            {
                return this._addressZipCode;
            }
            set
            {
                this._addressZipCode = value;
                this.SetIsModified("AddressZipCode");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("AddressCountry")]
        public virtual string AddressCountry
        {
            get
            {
                return this._addressCountry;
            }
            set
            {
                this._addressCountry = value;
                this.SetIsModified("AddressCountry");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("Deleted")]
        public virtual bool Deleted
        {
            get
            {
                return this._deleted;
            }
            set
            {
                this._deleted = value;
                this.SetIsModified("Deleted");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("InsertedDateTime")]
        public virtual System.DateTime InsertedDateTime
        {
            get
            {
                return this._insertedDateTime;
            }
            set
            {
                this._insertedDateTime = value;
                this.SetIsModified("InsertedDateTime");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ModifiedDateTime")]
        public virtual System.DateTime ModifiedDateTime
        {
            get
            {
                return this._modifiedDateTime;
            }
            set
            {
                this._modifiedDateTime = value;
                this.SetIsModified("ModifiedDateTime");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("AddressID")]
        [CommonLibrary.CustomAttributes.PrimaryKey()]
        public virtual System.Guid AddressID
        {
            get
            {
                return this._addressID;
            }
            set
            {
                this._addressID = value;
                this.SetIsModified("AddressID");
            }
        }
        
        public virtual Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this._isModifiedDictionary;
            }
            set
            {
                this._isModifiedDictionary = value;
            }
        }
        
        private void InitializeIsModifiedDictionary()
        {
            this.IsModifiedDictionary.Add("AddressTypeID", false);
            this.IsModifiedDictionary.Add("AddressStreet", false);
            this.IsModifiedDictionary.Add("AddressCity", false);
            this.IsModifiedDictionary.Add("AddressZipCode", false);
            this.IsModifiedDictionary.Add("AddressCountry", false);
            this.IsModifiedDictionary.Add("Deleted", false);
            this.IsModifiedDictionary.Add("InsertedDateTime", false);
            this.IsModifiedDictionary.Add("ModifiedDateTime", false);
            this.IsModifiedDictionary.Add("AddressID", false);
        }
        
        private void SetIsModified(string columnName)
        {
            if ((this.IsModifiedDictionary.ContainsKey(columnName) == true))
            {
                IsModifiedDictionary[columnName] = true;
            }
        }
    }
}
