//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSprocGenerator.Business.SingleTable.Bo
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/TestSprocGenerator.Business.SingleTable.B" +
        "o")]
    public partial class Country : TestSprocGenerator.Data.SingleTable.Dto.Country
    {
        
        private CommonLibrary.DatabaseSmoObjectsAndSettings DatabaseSmoObjectsAndSettingsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonLibrary.DatabaseSmoObjectsAndSettings DatabaseSmoObjectsAndSettings
        {
            get
            {
                return this.DatabaseSmoObjectsAndSettingsField;
            }
            set
            {
                this.DatabaseSmoObjectsAndSettingsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://schemas.datacontract.org/2004/07/TestSprocGenerator.Business.SingleTable.B" +
        "o")]
    public partial class City : TestSprocGenerator.Data.SingleTable.Dto.City
    {
        
        private CommonLibrary.DatabaseSmoObjectsAndSettings DatabaseSmoObjectsAndSettingsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonLibrary.DatabaseSmoObjectsAndSettings DatabaseSmoObjectsAndSettings
        {
            get
            {
                return this.DatabaseSmoObjectsAndSettingsField;
            }
            set
            {
                this.DatabaseSmoObjectsAndSettingsField = value;
            }
        }
    }
}
namespace TestSprocGenerator.Data.SingleTable.Dto
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/TestSprocGenerator.Data.SingleTable.Dto")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestSprocGenerator.Business.SingleTable.Bo.Country))]
    public partial class Country : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AbbreviationField;
        
        private short CountryIDField;
        
        private System.Guid CreatedByField;
        
        private System.Nullable<System.DateTime> CreatedDateField;
        
        private System.Collections.Generic.Dictionary<string, bool> IsModifiedDictionaryField;
        
        private string NameField;
        
        private string SubcodeField;
        
        private string ThreeCharISOCodeField;
        
        private char[] TwoCharISOCodeField;
        
        private System.Guid UpdatedByField;
        
        private System.Nullable<System.DateTime> UpdatedDateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Abbreviation
        {
            get
            {
                return this.AbbreviationField;
            }
            set
            {
                this.AbbreviationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CountryID
        {
            get
            {
                return this.CountryIDField;
            }
            set
            {
                this.CountryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this.IsModifiedDictionaryField;
            }
            set
            {
                this.IsModifiedDictionaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subcode
        {
            get
            {
                return this.SubcodeField;
            }
            set
            {
                this.SubcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ThreeCharISOCode
        {
            get
            {
                return this.ThreeCharISOCodeField;
            }
            set
            {
                this.ThreeCharISOCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char[] TwoCharISOCode
        {
            get
            {
                return this.TwoCharISOCodeField;
            }
            set
            {
                this.TwoCharISOCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UpdatedBy
        {
            get
            {
                return this.UpdatedByField;
            }
            set
            {
                this.UpdatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdatedDate
        {
            get
            {
                return this.UpdatedDateField;
            }
            set
            {
                this.UpdatedDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://schemas.datacontract.org/2004/07/TestSprocGenerator.Data.SingleTable.Dto")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestSprocGenerator.Business.SingleTable.Bo.City))]
    public partial class City : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CityCodeField;
        
        private int CityIDField;
        
        private System.Nullable<int> CountryIDField;
        
        private System.Guid CreatedByField;
        
        private System.Nullable<System.DateTime> CreatedDateField;
        
        private System.Collections.Generic.Dictionary<string, bool> IsModifiedDictionaryField;
        
        private string NameField;
        
        private System.Nullable<int> StateProvinceIDField;
        
        private System.Guid UpdatedByField;
        
        private System.Nullable<System.DateTime> UpdatedDateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityCode
        {
            get
            {
                return this.CityCodeField;
            }
            set
            {
                this.CityCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityID
        {
            get
            {
                return this.CityIDField;
            }
            set
            {
                this.CityIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CountryID
        {
            get
            {
                return this.CountryIDField;
            }
            set
            {
                this.CountryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this.IsModifiedDictionaryField;
            }
            set
            {
                this.IsModifiedDictionaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StateProvinceID
        {
            get
            {
                return this.StateProvinceIDField;
            }
            set
            {
                this.StateProvinceIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UpdatedBy
        {
            get
            {
                return this.UpdatedByField;
            }
            set
            {
                this.UpdatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdatedDate
        {
            get
            {
                return this.UpdatedDateField;
            }
            set
            {
                this.UpdatedDateField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICountryCityProvinceService")]
public interface ICountryCityProvinceService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryCityProvinceService/GetCountries", ReplyAction="http://tempuri.org/ICountryCityProvinceService/GetCountriesResponse")]
    TestSprocGenerator.Business.SingleTable.Bo.Country[] GetCountries();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryCityProvinceService/GetCities", ReplyAction="http://tempuri.org/ICountryCityProvinceService/GetCitiesResponse")]
    TestSprocGenerator.Business.SingleTable.Bo.City[] GetCities(System.Nullable<int> countryID);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICountryCityProvinceServiceChannel : ICountryCityProvinceService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CountryCityProvinceServiceClient : System.ServiceModel.ClientBase<ICountryCityProvinceService>, ICountryCityProvinceService
{
    
    public CountryCityProvinceServiceClient()
    {
    }
    
    public CountryCityProvinceServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CountryCityProvinceServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CountryCityProvinceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CountryCityProvinceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public TestSprocGenerator.Business.SingleTable.Bo.Country[] GetCountries()
    {
        return base.Channel.GetCountries();
    }
    
    public TestSprocGenerator.Business.SingleTable.Bo.City[] GetCities(System.Nullable<int> countryID)
    {
        return base.Channel.GetCities(countryID);
    }
}
