//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------







    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IProfileService")]
    public interface IProfileService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IProfileService/RetrieveProfileTypes", ReplyAction = "http://tempuri.org/IProfileService/RetrieveProfileTypesResponse")]
        TestSprocGenerator.Business.SingleTable.Bo.ProfileType[] RetrieveProfileTypes();
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfileServiceChannel : IProfileService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfileServiceClient : System.ServiceModel.ClientBase<IProfileService>, IProfileService
    {

        public ProfileServiceClient()
        {
        }

        public ProfileServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public ProfileServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public ProfileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public ProfileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public TestSprocGenerator.Business.SingleTable.Bo.ProfileType[] RetrieveProfileTypes()
        {
            return base.Channel.RetrieveProfileTypes();
        }
    }

