//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSprocGenerator.SingleTable.List
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Text;
    using CommonLibrary.Base.Database;
    
    
    [CommonLibrary.CustomAttributes.TableNameAttribute("Parent_Child")]
    public class Parent_Child : List<TestSprocGenerator.Data.SingleTable.Dto.Parent_Child>
    {
        
        private CommonLibrary.Base.Database.BaseDatabase _baseDatabase = new CommonLibrary.Base.Database.BaseDatabase();
        
        public Parent_Child(System.Data.SqlClient.SqlDataReader reader)
        {
            this.AddItemsToListBySqlDataReader(reader);
        }
        
        public Parent_Child()
        {
        }
        
        public virtual void AddItemsToListBySqlDataReader(System.Data.SqlClient.SqlDataReader reader)
        {
        
            TestSprocGenerator.Data.SingleTable.Dto.Parent_Child dto;
                using(reader)
                {

                while(reader.Read())
                {
            dto = new TestSprocGenerator.Data.SingleTable.Dto.Parent_Child();
                    dto.Parent_ChildID = 
                    _baseDatabase.retrieveGuidFromDataReader(reader.GetOrdinal("Parent_ChildID"), reader);
                    dto.Parent_ProfileID = 
                    _baseDatabase.retrieveGuidFromDataReader(reader.GetOrdinal("Parent_ProfileID"), reader);
                    dto.Child_ProfileID = 
                    _baseDatabase.retrieveGuidFromDataReader(reader.GetOrdinal("Child_ProfileID"), reader);
                    this.Add(dto);
                }

                }

        }
    }
}
