//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSprocGenerator.SingleTable.List
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Text;
    using CommonLibrary.Base.Database;
    
    
    [CommonLibrary.CustomAttributes.TableNameAttribute("PasswordResetRequest")]
    public class PasswordResetRequest : List<TestSprocGenerator.Data.SingleTable.Dto.PasswordResetRequest>
    {
        
        private CommonLibrary.Base.Database.BaseDatabase _baseDatabase = new CommonLibrary.Base.Database.BaseDatabase();
        
        public PasswordResetRequest(System.Data.SqlClient.SqlDataReader reader)
        {
            this.AddItemsToListBySqlDataReader(reader);
        }
        
        public PasswordResetRequest()
        {
        }
        
        public virtual void AddItemsToListBySqlDataReader(System.Data.SqlClient.SqlDataReader reader)
        {
        
            TestSprocGenerator.Data.SingleTable.Dto.PasswordResetRequest dto;
                using(reader)
                {

                while(reader.Read())
                {
            dto = new TestSprocGenerator.Data.SingleTable.Dto.PasswordResetRequest();
                    dto.PasswordResetRequestID = 
                    _baseDatabase.retrieveGuidFromDataReader(reader.GetOrdinal("PasswordResetRequestID"), reader);
                    dto.PasswordResetCode = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("PasswordResetCode"), reader);
                    dto.AccountID = 
                    _baseDatabase.retrieveGuidFromDataReader(reader.GetOrdinal("AccountID"), reader);
                    this.Add(dto);
                }

                }

        }
    }
}
