//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSprocGenerator.SingleTable.List
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Text;
    using CommonLibrary.Base.Database;
    
    
    [CommonLibrary.CustomAttributes.TableNameAttribute("CountryName")]
    public class CountryName : List<TestSprocGenerator.Data.SingleTable.Dto.CountryName>
    {
        
        private CommonLibrary.Base.Database.BaseDatabase _baseDatabase = new CommonLibrary.Base.Database.BaseDatabase();
        
        public CountryName(System.Data.SqlClient.SqlDataReader reader)
        {
            this.AddItemsToListBySqlDataReader(reader);
        }
        
        public CountryName()
        {
        }
        
        public virtual void AddItemsToListBySqlDataReader(System.Data.SqlClient.SqlDataReader reader)
        {
        
            TestSprocGenerator.Data.SingleTable.Dto.CountryName dto;
                using(reader)
                {

                while(reader.Read())
                {
            dto = new TestSprocGenerator.Data.SingleTable.Dto.CountryName();
                    dto.CountryID = 
                    _baseDatabase.resolveNullSmallInt(reader.GetOrdinal("CountryID"), reader);
                    dto.Name = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("Name"), reader);
                    dto.CountryNameID = 
                    _baseDatabase.resolveNullInt32(reader.GetOrdinal("CountryNameID"), reader);
                    this.Add(dto);
                }

                }

        }
    }
}
