//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSprocGenerator.SingleTable.List
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Text;
    using CommonLibrary.Base.Database;
    
    
    [CommonLibrary.CustomAttributes.TableNameAttribute("Employees")]
    public class Employees : List<TestSprocGenerator.Data.SingleTable.Dto.Employees>
    {
        
        private CommonLibrary.Base.Database.BaseDatabase _baseDatabase = new CommonLibrary.Base.Database.BaseDatabase();
        
        public Employees(System.Data.SqlClient.SqlDataReader reader)
        {
            this.AddItemsToListBySqlDataReader(reader);
        }
        
        public Employees()
        {
        }
        
        public virtual void AddItemsToListBySqlDataReader(System.Data.SqlClient.SqlDataReader reader)
        {
        
            TestSprocGenerator.Data.SingleTable.Dto.Employees dto;
                using(reader)
                {

                while(reader.Read())
                {
            dto = new TestSprocGenerator.Data.SingleTable.Dto.Employees();
                    dto.LastName = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("LastName"), reader);
                    dto.FirstName = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("FirstName"), reader);
                    dto.Title = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("Title"), reader);
                    dto.TitleOfCourtesy = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("TitleOfCourtesy"), reader);
                    dto.BirthDate = 
                    _baseDatabase.resolveNullDateTime(reader.GetOrdinal("BirthDate"), reader);
                    dto.HireDate = 
                    _baseDatabase.resolveNullDateTime(reader.GetOrdinal("HireDate"), reader);
                    dto.Address = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("Address"), reader);
                    dto.City = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("City"), reader);
                    dto.Region = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("Region"), reader);
                    dto.PostalCode = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("PostalCode"), reader);
                    dto.Country = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("Country"), reader);
                    dto.HomePhone = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("HomePhone"), reader);
                    dto.Extension = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("Extension"), reader);
                    dto.Photo = 
                    _baseDatabase.retrieveNullableImageFromDataReader(reader.GetOrdinal("Photo"), reader);
                    dto.Notes = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("Notes"), reader);
                    dto.ReportsTo = 
                    _baseDatabase.resolveNullInt32(reader.GetOrdinal("ReportsTo"), reader);
                    dto.PhotoPath = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("PhotoPath"), reader);
                    dto.EmployeeID = 
                    _baseDatabase.resolveNullInt32(reader.GetOrdinal("EmployeeID"), reader);
                    this.Add(dto);
                }

                }

        }
    }
}
