//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSprocGenerator.SingleTable.List
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Text;
    using CommonLibrary.Base.Database;
    
    
    [CommonLibrary.CustomAttributes.TableNameAttribute("Notification")]
    public class Notification : List<TestSprocGenerator.Data.SingleTable.Dto.Notification>
    {
        
        private CommonLibrary.Base.Database.BaseDatabase _baseDatabase = new CommonLibrary.Base.Database.BaseDatabase();
        
        public Notification(System.Data.SqlClient.SqlDataReader reader)
        {
            this.AddItemsToListBySqlDataReader(reader);
        }
        
        public Notification()
        {
        }
        
        public virtual void AddItemsToListBySqlDataReader(System.Data.SqlClient.SqlDataReader reader)
        {
        
            TestSprocGenerator.Data.SingleTable.Dto.Notification dto;
                using(reader)
                {

                while(reader.Read())
                {
            dto = new TestSprocGenerator.Data.SingleTable.Dto.Notification();
                    dto.ProfileIDFrom = 
                    _baseDatabase.retrieveGuidFromDataReader(reader.GetOrdinal("ProfileIDFrom"), reader);
                    dto.ProfileIDTo = 
                    _baseDatabase.retrieveGuidFromDataReader(reader.GetOrdinal("ProfileIDTo"), reader);
                    dto.Message = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("Message"), reader);
                    dto.Deleted = 
                    _baseDatabase.resolveNullBoolean(reader.GetOrdinal("Deleted"), reader);
                    dto.InsertedDatetime = 
                    _baseDatabase.resolveNullDateTime(reader.GetOrdinal("InsertedDatetime"), reader);
                    dto.ModifiedDateTime = 
                    _baseDatabase.resolveNullDateTime(reader.GetOrdinal("ModifiedDateTime"), reader);
                    dto.NotificationID = 
                    _baseDatabase.retrieveGuidFromDataReader(reader.GetOrdinal("NotificationID"), reader);
                    this.Add(dto);
                }

                }

        }
    }
}
