//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSprocGenerator.SingleTable.List
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Text;
    using CommonLibrary.Base.Database;
    
    
    [CommonLibrary.CustomAttributes.TableNameAttribute("Shippers")]
    public class Shippers : List<TestSprocGenerator.Data.SingleTable.Dto.Shippers>
    {
        
        private CommonLibrary.Base.Database.BaseDatabase _baseDatabase = new CommonLibrary.Base.Database.BaseDatabase();
        
        public Shippers(System.Data.SqlClient.SqlDataReader reader)
        {
            this.AddItemsToListBySqlDataReader(reader);
        }
        
        public Shippers()
        {
        }
        
        public virtual void AddItemsToListBySqlDataReader(System.Data.SqlClient.SqlDataReader reader)
        {
        
            TestSprocGenerator.Data.SingleTable.Dto.Shippers dto;
                using(reader)
                {

                while(reader.Read())
                {
            dto = new TestSprocGenerator.Data.SingleTable.Dto.Shippers();
                    dto.CompanyName = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("CompanyName"), reader);
                    dto.Phone = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("Phone"), reader);
                    dto.ShipperID = 
                    _baseDatabase.resolveNullInt32(reader.GetOrdinal("ShipperID"), reader);
                    this.Add(dto);
                }

                }

        }
    }
}
