//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSprocGenerator.SingleTable.List
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Text;
    using CommonLibrary.Base.Database;
    
    
    [CommonLibrary.CustomAttributes.TableNameAttribute("Territories")]
    public class Territories : List<TestSprocGenerator.Data.SingleTable.Dto.Territories>
    {
        
        private CommonLibrary.Base.Database.BaseDatabase _baseDatabase = new CommonLibrary.Base.Database.BaseDatabase();
        
        public Territories(System.Data.SqlClient.SqlDataReader reader)
        {
            this.AddItemsToListBySqlDataReader(reader);
        }
        
        public Territories()
        {
        }
        
        public virtual void AddItemsToListBySqlDataReader(System.Data.SqlClient.SqlDataReader reader)
        {
        
            TestSprocGenerator.Data.SingleTable.Dto.Territories dto;
                using(reader)
                {

                while(reader.Read())
                {
            dto = new TestSprocGenerator.Data.SingleTable.Dto.Territories();
                    dto.TerritoryDescription = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("TerritoryDescription"), reader);
                    dto.RegionID = 
                    _baseDatabase.resolveNullInt32(reader.GetOrdinal("RegionID"), reader);
                    dto.TerritoryID = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("TerritoryID"), reader);
                    this.Add(dto);
                }

                }

        }
    }
}
