//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSprocGenerator.Data.SingleTable.Dto
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/TestSprocGenerator.Data.SingleTable.Dto")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestSprocGenerator.Business.SingleTable.Bo.Account))]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AccountCodeField;
        
        private System.Guid AccountIDField;
        
        private string AccountPasswordField;
        
        private string AccountUsernameField;
        
        private bool DeletedField;
        
        private System.DateTime InsertedDateTimeField;
        
        private System.Collections.Generic.Dictionary<string, bool> IsModifiedDictionaryField;
        
        private System.DateTime ModifiedDateTimeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountCode
        {
            get
            {
                return this.AccountCodeField;
            }
            set
            {
                this.AccountCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AccountID
        {
            get
            {
                return this.AccountIDField;
            }
            set
            {
                this.AccountIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountPassword
        {
            get
            {
                return this.AccountPasswordField;
            }
            set
            {
                this.AccountPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountUsername
        {
            get
            {
                return this.AccountUsernameField;
            }
            set
            {
                this.AccountUsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InsertedDateTime
        {
            get
            {
                return this.InsertedDateTimeField;
            }
            set
            {
                this.InsertedDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this.IsModifiedDictionaryField;
            }
            set
            {
                this.IsModifiedDictionaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDateTime
        {
            get
            {
                return this.ModifiedDateTimeField;
            }
            set
            {
                this.ModifiedDateTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/TestSprocGenerator.Data.SingleTable.Dto")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestSprocGenerator.Business.SingleTable.Bo.Person))]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool DeletedField;
        
        private System.DateTime InsertedDateTimeField;
        
        private System.Collections.Generic.Dictionary<string, bool> IsModifiedDictionaryField;
        
        private System.DateTime ModifiedDateTimeField;
        
        private string PersonFirstNameField;
        
        private System.Guid PersonIDField;
        
        private string PersonLastNameField;
        
        private string PersonMiddleInitialsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InsertedDateTime
        {
            get
            {
                return this.InsertedDateTimeField;
            }
            set
            {
                this.InsertedDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this.IsModifiedDictionaryField;
            }
            set
            {
                this.IsModifiedDictionaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDateTime
        {
            get
            {
                return this.ModifiedDateTimeField;
            }
            set
            {
                this.ModifiedDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonFirstName
        {
            get
            {
                return this.PersonFirstNameField;
            }
            set
            {
                this.PersonFirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonID
        {
            get
            {
                return this.PersonIDField;
            }
            set
            {
                this.PersonIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonLastName
        {
            get
            {
                return this.PersonLastNameField;
            }
            set
            {
                this.PersonLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonMiddleInitials
        {
            get
            {
                return this.PersonMiddleInitialsField;
            }
            set
            {
                this.PersonMiddleInitialsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/TestSprocGenerator.Data.SingleTable.Dto")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestSprocGenerator.Business.SingleTable.Bo.Address))]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddressCityField;
        
        private string AddressCountryField;
        
        private System.Guid AddressIDField;
        
        private string AddressStreetField;
        
        private System.Guid AddressTypeIDField;
        
        private string AddressZipCodeField;
        
        private bool DeletedField;
        
        private System.DateTime InsertedDateTimeField;
        
        private System.Collections.Generic.Dictionary<string, bool> IsModifiedDictionaryField;
        
        private System.DateTime ModifiedDateTimeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressCity
        {
            get
            {
                return this.AddressCityField;
            }
            set
            {
                this.AddressCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressCountry
        {
            get
            {
                return this.AddressCountryField;
            }
            set
            {
                this.AddressCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AddressID
        {
            get
            {
                return this.AddressIDField;
            }
            set
            {
                this.AddressIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressStreet
        {
            get
            {
                return this.AddressStreetField;
            }
            set
            {
                this.AddressStreetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AddressTypeID
        {
            get
            {
                return this.AddressTypeIDField;
            }
            set
            {
                this.AddressTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressZipCode
        {
            get
            {
                return this.AddressZipCodeField;
            }
            set
            {
                this.AddressZipCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InsertedDateTime
        {
            get
            {
                return this.InsertedDateTimeField;
            }
            set
            {
                this.InsertedDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this.IsModifiedDictionaryField;
            }
            set
            {
                this.IsModifiedDictionaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDateTime
        {
            get
            {
                return this.ModifiedDateTimeField;
            }
            set
            {
                this.ModifiedDateTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneNumber", Namespace="http://schemas.datacontract.org/2004/07/TestSprocGenerator.Data.SingleTable.Dto")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestSprocGenerator.Business.SingleTable.Bo.PhoneNumber))]
    public partial class PhoneNumber : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool DeletedField;
        
        private System.DateTime InsertedDateTimeField;
        
        private System.Collections.Generic.Dictionary<string, bool> IsModifiedDictionaryField;
        
        private System.DateTime ModifiedDateTimeField;
        
        private System.Guid PhoneNumberIDField;
        
        private System.Guid PhoneNumberTypeIDField;
        
        private string PhoneNumber_PropertyField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InsertedDateTime
        {
            get
            {
                return this.InsertedDateTimeField;
            }
            set
            {
                this.InsertedDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this.IsModifiedDictionaryField;
            }
            set
            {
                this.IsModifiedDictionaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDateTime
        {
            get
            {
                return this.ModifiedDateTimeField;
            }
            set
            {
                this.ModifiedDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PhoneNumberID
        {
            get
            {
                return this.PhoneNumberIDField;
            }
            set
            {
                this.PhoneNumberIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PhoneNumberTypeID
        {
            get
            {
                return this.PhoneNumberTypeIDField;
            }
            set
            {
                this.PhoneNumberTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber_Property
        {
            get
            {
                return this.PhoneNumber_PropertyField;
            }
            set
            {
                this.PhoneNumber_PropertyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailAddress", Namespace="http://schemas.datacontract.org/2004/07/TestSprocGenerator.Data.SingleTable.Dto")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestSprocGenerator.Business.SingleTable.Bo.EmailAddress))]
    public partial class EmailAddress : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid EmailAddressIDField;
        
        private string EmailAddress_PropertyField;
        
        private System.Collections.Generic.Dictionary<string, bool> IsModifiedDictionaryField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid EmailAddressID
        {
            get
            {
                return this.EmailAddressIDField;
            }
            set
            {
                this.EmailAddressIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress_Property
        {
            get
            {
                return this.EmailAddress_PropertyField;
            }
            set
            {
                this.EmailAddress_PropertyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this.IsModifiedDictionaryField;
            }
            set
            {
                this.IsModifiedDictionaryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfileType", Namespace="http://schemas.datacontract.org/2004/07/TestSprocGenerator.Data.SingleTable.Dto")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestSprocGenerator.Business.SingleTable.Bo.ProfileType))]
    public partial class ProfileType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool DeletedField;
        
        private System.DateTime InsertedDateTimeField;
        
        private System.Collections.Generic.Dictionary<string, bool> IsModifiedDictionaryField;
        
        private System.DateTime ModifiedDateTimeField;
        
        private string ProfileNameField;
        
        private System.Guid ProfileTypeIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InsertedDateTime
        {
            get
            {
                return this.InsertedDateTimeField;
            }
            set
            {
                this.InsertedDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this.IsModifiedDictionaryField;
            }
            set
            {
                this.IsModifiedDictionaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDateTime
        {
            get
            {
                return this.ModifiedDateTimeField;
            }
            set
            {
                this.ModifiedDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfileName
        {
            get
            {
                return this.ProfileNameField;
            }
            set
            {
                this.ProfileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProfileTypeID
        {
            get
            {
                return this.ProfileTypeIDField;
            }
            set
            {
                this.ProfileTypeIDField = value;
            }
        }
    }
}
namespace TestSprocGenerator.Business.SingleTable.Bo
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/TestSprocGenerator.Business.SingleTable.B" +
        "o")]
    public partial class Account : TestSprocGenerator.Data.SingleTable.Dto.Account
    {
        
        private CommonLibrary.DatabaseSmoObjectsAndSettings DatabaseSmoObjectsAndSettingsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonLibrary.DatabaseSmoObjectsAndSettings DatabaseSmoObjectsAndSettings
        {
            get
            {
                return this.DatabaseSmoObjectsAndSettingsField;
            }
            set
            {
                this.DatabaseSmoObjectsAndSettingsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/TestSprocGenerator.Business.SingleTable.B" +
        "o")]
    public partial class Person : TestSprocGenerator.Data.SingleTable.Dto.Person
    {
        
        private CommonLibrary.DatabaseSmoObjectsAndSettings DatabaseSmoObjectsAndSettingsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonLibrary.DatabaseSmoObjectsAndSettings DatabaseSmoObjectsAndSettings
        {
            get
            {
                return this.DatabaseSmoObjectsAndSettingsField;
            }
            set
            {
                this.DatabaseSmoObjectsAndSettingsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/TestSprocGenerator.Business.SingleTable.B" +
        "o")]
    public partial class Address : TestSprocGenerator.Data.SingleTable.Dto.Address
    {
        
        private CommonLibrary.DatabaseSmoObjectsAndSettings DatabaseSmoObjectsAndSettingsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonLibrary.DatabaseSmoObjectsAndSettings DatabaseSmoObjectsAndSettings
        {
            get
            {
                return this.DatabaseSmoObjectsAndSettingsField;
            }
            set
            {
                this.DatabaseSmoObjectsAndSettingsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneNumber", Namespace="http://schemas.datacontract.org/2004/07/TestSprocGenerator.Business.SingleTable.B" +
        "o")]
    public partial class PhoneNumber : TestSprocGenerator.Data.SingleTable.Dto.PhoneNumber
    {
        
        private CommonLibrary.DatabaseSmoObjectsAndSettings DatabaseSmoObjectsAndSettingsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonLibrary.DatabaseSmoObjectsAndSettings DatabaseSmoObjectsAndSettings
        {
            get
            {
                return this.DatabaseSmoObjectsAndSettingsField;
            }
            set
            {
                this.DatabaseSmoObjectsAndSettingsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailAddress", Namespace="http://schemas.datacontract.org/2004/07/TestSprocGenerator.Business.SingleTable.B" +
        "o")]
    public partial class EmailAddress : TestSprocGenerator.Data.SingleTable.Dto.EmailAddress
    {
        
        private CommonLibrary.DatabaseSmoObjectsAndSettings DatabaseSmoObjectsAndSettingsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonLibrary.DatabaseSmoObjectsAndSettings DatabaseSmoObjectsAndSettings
        {
            get
            {
                return this.DatabaseSmoObjectsAndSettingsField;
            }
            set
            {
                this.DatabaseSmoObjectsAndSettingsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfileType", Namespace="http://schemas.datacontract.org/2004/07/TestSprocGenerator.Business.SingleTable.B" +
        "o")]
    public partial class ProfileType : TestSprocGenerator.Data.SingleTable.Dto.ProfileType
    {
        
        private CommonLibrary.DatabaseSmoObjectsAndSettings DatabaseSmoObjectsAndSettingsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonLibrary.DatabaseSmoObjectsAndSettings DatabaseSmoObjectsAndSettings
        {
            get
            {
                return this.DatabaseSmoObjectsAndSettingsField;
            }
            set
            {
                this.DatabaseSmoObjectsAndSettingsField = value;
            }
        }
    }
}
namespace CommonLibrary
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatabaseSmoObjectsAndSettings", Namespace="http://schemas.datacontract.org/2004/07/CommonLibrary")]
    public partial class DatabaseSmoObjectsAndSettings : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IRegistrationService")]
public interface IRegistrationService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationService/Register", ReplyAction="http://tempuri.org/IRegistrationService/RegisterResponse")]
    bool Register(TestSprocGenerator.Business.SingleTable.Bo.Account accountInfo, TestSprocGenerator.Business.SingleTable.Bo.Person personInfo, TestSprocGenerator.Business.SingleTable.Bo.Address addressInfo, TestSprocGenerator.Business.SingleTable.Bo.PhoneNumber phoneNumberInfo, TestSprocGenerator.Business.SingleTable.Bo.EmailAddress emailAddressInfo, TestSprocGenerator.Business.SingleTable.Bo.ProfileType profileType);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRegistrationServiceChannel : IRegistrationService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RegistrationServiceClient : System.ServiceModel.ClientBase<IRegistrationService>, IRegistrationService
{
    
    public RegistrationServiceClient()
    {
    }
    
    public RegistrationServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RegistrationServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RegistrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RegistrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool Register(TestSprocGenerator.Business.SingleTable.Bo.Account accountInfo, TestSprocGenerator.Business.SingleTable.Bo.Person personInfo, TestSprocGenerator.Business.SingleTable.Bo.Address addressInfo, TestSprocGenerator.Business.SingleTable.Bo.PhoneNumber phoneNumberInfo, TestSprocGenerator.Business.SingleTable.Bo.EmailAddress emailAddressInfo, TestSprocGenerator.Business.SingleTable.Bo.ProfileType profileType)
    {
        return base.Channel.Register(accountInfo, personInfo, addressInfo, phoneNumberInfo, emailAddressInfo, profileType);
    }
}
